// Extension for Opera Browser - Magic Actions for YouTube™ - CHROMEACTIONS.COM - Copyright 2015 Vlad and Serge Strukoff - All Rights Reserved
chrome.runtime.onStartup.addListener(function(){});
(function(){function l(d){var e={ver:m,nv:3,uid:"",mwvc:!0,color:"yellow",mwvct:0,mwvci:2,gap:10,hq:!0,hqi:"large",pause:!1,plist:!1,buf:!1,buf1:!1,loop:!1,hide:!1,ha:!1,anns:!0,cin:!0,cina:!1,cini:2,cinf:!1,cinc:1,cins:"",pt:!1,pti:0,ww:!1,wide:!1,h0:!1,h1:!1,h2:!1,h3:!1,h4:!1,h5:!1,h6:!1,h7:!1,h8:!1,a0:!0,a1:!1,a2:!1,a3:!1,a4:!0,a5:!1,ui:0,c0:!1,c1:!1,c2:!1,c3:!1,c4:!1,f0:!0,mrl:!0};a=d;if(void 0===a||null===a||"object"!==typeof a||void 0===a.ver)a={nv:3,uid:q()};for(var b in e)void 0===a[b]&&(a[b]=
e[b]);for(b in a)void 0===e[b]&&(delete a[b],chrome.storage.local.remove(b));for(b in a)typeof a[b]!==typeof e[b]&&(a[b]=e[b]);r();document.cookie&&-1<document.cookie.indexOf("s=1")?(k=parseInt(localStorage.st),s()):(document.cookie="s=1; expires=0; path=/",localStorage.st=k,s(),3==a.nv?t(1):a.ver!==m?(d=k,e=d+18144E5,a.nv=Math.floor(Math.random()*(e-d+1))+d,a.ver=m,h()):0<a.nv&&a.nv<k&&t())}function s(){chrome.runtime.onMessage.addListener(x);a.a0&&a.a3&&y()}function t(d){chrome.tabs.create({url:"http://www.chromeactions.com"});
d?(a.nv=0,h(),n({ea:"install"}),chrome.tabs.create({url:"http://www.hotcleaner.com/clickclean/install-magic.html"})):(a.nv=1,h(),n({ea:"update"}),u())}function r(d){function e(a){return(Array(8).join("0")+a.toString(16)).slice(-8)}d=chrome.runtime.getURL("");var b=0,c=0,f=0,g="red LightPink orange lime GreenYellow yellow gold DodgerBlue aqua magenta DeepPink white".split(" ").indexOf(a.color),h="highres hd2880 hd2160 hd1440 hd1080 hd720 large medium small tiny".split(" ").indexOf(a.hqi),b=b|a.h0<<
19,b=b|a.h1<<18,b=b|a.h2<<17,b=b|a.h3<<16,b=b|a.h4<<15,b=b|a.h5<<14,b=b|a.h6<<13,b=b|a.h7<<12,b=b|a.h8<<11,b=b|a.a0<<10,b=b|a.a1<<9,b=b|a.a2<<8,b=b|a.a3<<7,b=b|a.a4<<6,b=b|a.a5<<5,b=b|a.c0<<4,b=b|a.c1<<3,b=b|a.c2<<2,b=b|a.c3<<1,b=b|a.c4,c=c|a.ui<<25,c=c|a.wide<<24,c=c|a.ww<<23,c=c|a.mwvc<<22,c=c|(0>g?4:g)<<18|a.mwvct<<17,c=c|a.mwvci<<15,c=c|a.gap<<10,c=c|a.pause<<9,c=c|a.plist<<8,c=c|a.buf<<7,c=c|a.buf1<<6,c=c|a.loop<<5,c=c|a.hide<<4,c=c|a.ha<<3,c=c|a.anns<<2,c=c|a.pt<<1,c=c|a.pti,f=f|a.mrl<<18,f=
f|a.f0<<17,f=f|a.hq<<16,f=f|(0>h?5:h)<<12|a.cin<<11,f=f|a.cina<<10,f=f|a.cini<<8,f=f|a.cinf<<7,f=f|(63<a.cinc?63:a.cinc);d="0"+e(b)+e(c)+e(f)+d+(62<a.cinc?a.cins:"");p='var e=document.createEvent("CustomEvent");e.initCustomEvent("mafy",!1,!1,"'+d+'");window.dispatchEvent(e);if(window.sessionStorage)window.sessionStorage.mafy="'+d+'"'}function h(){a.a0&&a.a4||(a.ui=0);try{chrome.storage.local.set(a)}catch(d){v(d,1)}try{localStorage.setItem("opt",JSON.stringify(a))}catch(e){v(e,1)}r(1);chrome.tabs.query({windowType:"normal",
url:"*://*.youtube.com/*",status:"complete"},function(a){for(var d=0,e=a.length;d<e;d++)chrome.tabs.executeScript(a[d].id,{code:p.replace('"0','"1')})})}function x(d,e,b){32==d&&(chrome.tabs.executeScript(e.tab.id,{code:p,runAt:"document_start"}),chrome.pageAction.show(e.tab.id));try{d=JSON.parse(d)}catch(c){return}0==d.id?b({opt:a,url:e.tab.url}):1==d.id?n(d.ga):2==d.id?chrome.tabs.create({url:d.url}):3==d.id?(a=d.opt,h()):4==d.id?(a[d.name]=d.value,h()):5==d.id?b({value:a[d.name]}):6==d.id?z(d.v):
7==d.id?u():9==d.id?b(w):11==d.id&&chrome.windows.update(e.tab.windowId,{state:d.v?"fullscreen":"maximized"});return!0}function z(a){chrome.windows.getLastFocused({populate:!1},function(e){w={w:a[0],h:a[1],pic:a[2],vid:a[3],lic:a[4],t:a[5]};chrome.tabs.query({url:"http://www.chromeactions.com/capture-snapshot-video-frames.html"},function(a){a&&a.length?chrome.tabs.update(a[0].id,{active:!0},function(){chrome.tabs.executeScript(a[0].id,{file:"cap6895.js"})}):chrome.tabs.create({active:!0,url:"http://www.chromeactions.com/capture-snapshot-video-frames.html"})})})}
function u(){function a(){chrome.tabs.get(e,function(c){"complete"==c.status?0!=c.title.indexOf("Magic")&&chrome.tabs.update(e,{url:b}):setTimeout(a,1E3)})}var e,b="opt.html?s=689"+(new Date).getDate(),c=navigator.onLine?"http://www.chromeactions.com/magic-options.html":b;chrome.tabs.query({url:c},function(b){b&&b.length?chrome.tabs.update(b[0].id,{active:!0},function(a){chrome.windows.update(a.windowId,{focused:!0})}):chrome.tabs.create({url:c,active:!0},function(b){e=b.id;setTimeout(a,3E3)})})}
function v(a,e){console.log("Magic: "+["Could't read preferences.","Could't write preferences."][e]+" "+a.name+": "+a.message)}function A(a,e){if(7840==a.menuItemId){var b="http://www.youtube.com/results?search_query="+encodeURIComponent(a.selectionText);0==e.url.indexOf("http://www.youtube.com/")?chrome.tabs.update({url:b}):chrome.tabs.create({url:b,selected:!0})}}function y(){chrome.contextMenus.create({id:"7840",title:"Search YouTube for %s",contexts:["selection"]},function(){chrome.contextMenus.onClicked.addListener(A)})}
function n(d){var e=d.ec?d.ec:"app",b=d.ea?d.ea:"unk";d=d.el?d.el:"mafo 6.8.9.5";a.uid||(a.uid=q());B("POST","http://www.google-analytics.com/collect","v=1&tid=UA-326771-7&cid="+a.uid+"&t=event&ec="+e+"&ea="+b+"&el="+d,"text",function(){})}function B(a,e,b,c,f){var g=new XMLHttpRequest;g.open(a,e,!0);c&&(g.responseType=c);g.onload=function(a){200==this.status?f(this.response):f(null)};g.onerror=function(){f(null)};g.onabort=function(){f(null)};g.send(b)}function q(){var a=Math.random,e=(4294967296*
a()>>>0).toString(16),b=((4294967296*a()&4294922239|16384)>>>0).toString(16),c=((4294967296*a()&3221225471|2147483648)>>>0).toString(16),a=(4294967296*a()>>>0).toString(16);8>e.length&&(e=("0000000"+e).slice(-8));8>b.length&&(b=("0000000"+b).slice(-8));8>c.length&&(c=("0000000"+c).slice(-8));8>a.length&&(a=("0000000"+a).slice(-8));return[e,b.slice(0,4),b.slice(4),c.slice(0,4),c.slice(4)+a].join("-")}var m="6.8.9.5",k=Date.now(),w,a,p;chrome.storage.local.get(null,function(a){if(chrome.runtime.lastError)if(a=
localStorage.getItem("opt"),void 0===a)l();else{try{a=JSON.parse(a)}catch(e){a=void 0}l(a)}else l(a)})})();
